# Settings for JVM Metaspace and Heap
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8

android.useAndroidX=true
android.enableJetifier=true

# Fix for "Could not connect to Kotlin compile daemon"
# Switching execution strategy to 'in-process' bypasses the daemon connection issues
org.gradle.daemon=true
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=true

# Fallback strategy
kotlin.daemon.useFallbackStrategy=true
