// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnjXU5joIcOF8s4DxO5tgp1Ou7CfOyMSQ',
    appId: '1:524389477177:web:715ff440e20fbe8160d6e8',
    messagingSenderId: '524389477177',
    projectId: 'almaqraa-9c0e5',
    authDomain: 'almaqraa-9c0e5.firebaseapp.com',
    storageBucket: 'almaqraa-9c0e5.firebasestorage.app',
    measurementId: 'G-KBXXDQSSJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo98JWjm5kgZmd38ncBnvSY41Nkd7bIhw',
    appId: '1:524389477177:android:fde9af513cc820a760d6e8',
    messagingSenderId: '524389477177',
    projectId: 'almaqraa-9c0e5',
    storageBucket: 'almaqraa-9c0e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLBeRGwHdPQI8yXj8O0sqtRxpKPsZJbcM',
    appId: '1:524389477177:ios:4309fa4d1eb266d060d6e8',
    messagingSenderId: '524389477177',
    projectId: 'almaqraa-9c0e5',
    storageBucket: 'almaqraa-9c0e5.firebasestorage.app',
    iosBundleId: 'com.example.alMaqraa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLBeRGwHdPQI8yXj8O0sqtRxpKPsZJbcM',
    appId: '1:524389477177:ios:4309fa4d1eb266d060d6e8',
    messagingSenderId: '524389477177',
    projectId: 'almaqraa-9c0e5',
    storageBucket: 'almaqraa-9c0e5.firebasestorage.app',
    iosBundleId: 'com.example.alMaqraa',
  );

  static const
   FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnjXU5joIcOF8s4DxO5tgp1Ou7CfOyMSQ',
    appId: '1:524389477177:web:72a41ad0510e93d860d6e8',
    messagingSenderId: '524389477177',
    projectId: 'almaqraa-9c0e5',
    authDomain: 'almaqraa-9c0e5.firebaseapp.com',
    storageBucket: 'almaqraa-9c0e5.firebasestorage.app',
    measurementId: 'G-2KS0QE8WR6',
  );
}
